language: python

dist: xenial

sudo: required

install:
    # Package still not available, see: https://github.com/gohugoio/hugo/issues/3608
    # - sudo apt install python-pygments
    # Alternative solution
    - sudo pip install pygments\<2.3
    - wget https://mirror.csclub.uwaterloo.ca/debian/pool/main/libs/libsass/libsass1_3.5.5-4_amd64.deb -O /tmp/libsass1.deb && sudo dpkg -i /tmp/libsass1.deb
    - wget https://mirror.csclub.uwaterloo.ca/debian/pool/main/h/hugo/hugo_0.55.6+really0.54.0-1_amd64.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb


# Build the website
script:
    - cd hugo_site && hugo -v
